site_name: Val-de-Reuil docs
site_url: https://fofomalo.github.io/vdr_docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.hightlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
      primary: teal
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.details
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ' '
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike

copyright: |
  &copy; 2023 Val-de-Reuil <a href="https://github.com/FofoMalo" target "_blank" rel="glp3">Florent Malo</a>