site_name: Val-de-Reuil docs
site_url: https://fofomalo.github.io/vdr_docs/
# repo
repo_name: FofoMalo/vdr_docs
repo_url: https://github.com/FofoMalo/vdr_docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.hightlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
      primary: teal
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: FofoMalo
      repo: vdr_docs
extra:
  version:
    provider: mike
  annotate:
    json: [.s2]

# nav
nav:
  - Home: index.md
  - Cartographie_SI: Cartographie_SI.md
  - Intranet_Vdr: Intranet_Vdr.md
  - OpenData_Vdr: OpenData_Vdr.md
  - RGPD_Vdr: RGPD_Vdr.md


copyright: |
  &copy; 2023 Val-de-Reuil <a href="https://github.com/FofoMalo" target "_blank" rel="glp3">Florent Malo</a>